package com.ipaper.myapp;

public enum Language {
	ASSAMESE, BENGALI, ENGLISH, GUJARATI, HINDI, KANNADA, KASHMIRI, KONKANI, MALAYALAM, MANIPURI, MARATHI, NEPALI, ORIYA, PUNJABI, SANSKRIT, SINDHI, TAMIL, TELUGU, URDU
}
